### PR TITLE
Greeter: separate greeters into separate database from helpers

### PR DESCRIPTION
**Pull request by mistydemeo**
I don't normally ask for review when pushing zoia plugins, but I wanted to make sure there was consensus on this change before merging.

Zoia's helpers plugin currently notifies all of the helpers any time an unrecognized user logs in. A few of the helpers, including me, have been complaining about the volume of PMs; I'm happy to be a helper for any user who needs it, but this volume of messaging's too high for me. After some discussion in #code4lib, it was suggested we break out the "greeter" part into a separate database, so that helpers aren't automatically also greeters.

This adds a separate greeter database along with a new `addgreeter` command, and `greeters` to list the greeters currently in the room.

cc @thatandromeda, @mbklein re: the discussion in IRC earlier

### CODE REVIEW

**Comment by thatandromeda** [comment]
:+1: 

Maybe "greeter add" syntax, by parallel with other plugins, instead of "addgreeter"?

**Comment by mistydemeo** [comment]
`add` is already taken by the command to add people to the blacklist; I could rename that to open the slot though.

**Comment by mbklein** [comment]
Which blacklist? An add command within the context of the Greeter plugin should respond to `@greeter add`. Simply using `@add` will return a list of plugins that contain an `add` command and ask the user to disambiguate.

**Comment by mistydemeo** [comment]
This one: https://github.com/code4lib/supybot-plugins/blob/master/plugins/Greeter/plugin.py#L143-L158

`greeter add` is used for the greeter plugin's ignore list.

**Comment by mistydemeo** [comment]
Could rename `greeter add` to `greeter ignore`? I don't think it's widely used at the moment so it probably wouldn't add much confusion.

**Comment by mbklein** [comment]
Ah, yes, I see it now. I like the idea of `greeter ignore`

**Comment by mistydemeo** [comment]
All right, updated to turn `greeter add` into `greeter ignore` and `greeter remove` into `greeter unignore`, then switched the add/remove greeters commands to `add/remove`. I'll merge this if there aren't any other concerns!

**Pull request merged**
